### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by ericbf** [MichaelSeeberger/Markdown-Viewer#1]
How can one install this?

Does it require  manual building through Xcode? Or is there a download?

**Comment by MichaelSeeberger** [comment]
I created a downloadable file: https://www.filehosting.org/file/details/782916/Markdown%20Viewer.zip

Please note that I haven't worked on this project in 7 years! There are most likely better markdown viewers available.

**Comment by ericbf** [comment]
Thanks! What caught my eye was the quick look integration 😀. We shall see.

**Comment by MichaelSeeberger** [comment]
The quick look integration still works, I tested it today on macOS 10.14. Let me know if there is a problem!

**Comment by ericbf** [comment]
Will do! Looks great so far.
